services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: daily-local-web
    depends_on:
      - db
    volumes:
      - .:/app:z
      - /app/.venv
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'

  db:
    image: postgres:17
    container_name: daily-local-db
    volumes:
      - postgres_local_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.local/.postgres
    ports:
      - 5432:5432

volumes:
  postgres_local_data:
