x-app: &default-app
  build:
    context: .
    dockerfile: ./compose/local/django/Dockerfile
  restart: "unless-stopped"
  volumes:
    - .:/app:z
    - /app/.venv
  env_file:
    - .envs/.local/.django
    - .envs/.local/.postgres
  depends_on:
    - db

services:
  web:
    <<: *default-app
    container_name: daily-local-web
    ports:
      - "8000:8000"

  tailwind:
    <<: *default-app
    container_name: kara-local-tailwind
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true

  db:
    image: postgres:17
    container_name: daily-local-db
    volumes:
      - postgres_local_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.local/.postgres
    ports:
      - 5432:5432

volumes:
  postgres_local_data:
